myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,re_path
from accounts import views as account_views
#from accounts.views import signup it will create the clash on boards view and accout view
from boards import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('signup/',account_views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    re_path(r'^boards/(?P<pk>\d+)/$',views.board_topics,name='board_topics'),
    re_path(r'^boards/(?P<pk>\d+)/new/$',views.new_topic,name='new_topic'),

]

myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/boards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    name=models.CharField(max_length=30,unique=True)
    description=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject=models.CharField(max_length=200)
    last_updated=models.DateTimeField(auto_now_add=True)
    board=models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)
    starter=models.ForeignKey(User,related_name='topics',on_delete=models.CASCADE)

class Post(models.Model):
    message=models.TextField(max_length=4000)
    topic=models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(null=True)
    created_by=models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    update_by=models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)

myproject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email=forms.CharField(max_length=400,required=True,widget=forms.EmailInput())
    
    class Meta:
        model=User
        fields=['username','email','password1','password2']

myproject/boards/forms.py
from django import forms
from .models import Topic

class NewTopicForm(forms.ModelForm):
    message=forms.CharField(
        widget=forms.Textarea(
            attrs={'rows':5,'placeholder':'what is on your mind'}
        ),
        max_length=4000,
        help_text='The max length is 4000'   #It also handles help texts, which can be defined both in a Form class or in a Model class:
        )

    class Meta:
        model=Topic
        fields=['subject','message']

myproject/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login 
from .forms import SignUpForm
# Create your views here.
def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user) #this login the user
            return redirect('home') #this code redirects to the home view 

    else:
        form=SignUpForm()

    
    return render(request,'signup.html',{'form':form})

myproject/boards/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Board
from django.http import Http404
from django.contrib.auth.models import User
from .models import Board,Topic,Post
from .forms import NewTopicForm
# Create your views here.

def home(request):
    boards=Board.objects.all()
    return render(request,'home.html',{'boards':boards})

def board_topics(request,pk):
    board=get_object_or_404(Board,pk=pk)
    return render(request,'topics.html',{'board':board})

def new_topic(request,pk):
    board=get_object_or_404(Board,pk=pk)
    user=User.objects.first() #get currently logged in users
    if request.method=='POST':
        form=NewTopicForm(request.POST)  #instantiate a form instance passing the POST data to the form
        if form.is_valid():
            topic=form.save(commit=False)
            """    
                This save() method accepts an optional commit keyword argument, which accepts either True or False.
                If you call save() with commit=False, then it will return an object that hasn’t yet been saved to the
                database. In this case, it’s up to you to call save() on the resulting model instance. This is useful 
                if you want to do custom processing on the object before saving it, or if you want to use one of the 
                specialized model saving options. commit is True by default.
            """
            #HERE if we haven't commited false we couldn't have beeen able to update topics field
            topic.board=board
            topic.starter=user
            topic.save()
            post=Post.objects.create(
                message=form.cleaned_data.get('message'),
                created_by=user,
                topic=topic
            )
            return redirect('board_topics',pk=board.pk) #edirect to the created topic page
    else:
        form=NewTopicForm()
    return render(request,'new_topic.html',{'board':board,'form':form})

myproject/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
 
    {% block stylesheet %}  {% endblock %}


  </head>
  <body>
      {% block body %}
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="#">My account</a>
                    <a class="dropdown-item" href="#">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                  </div>
                </li>
              </ul>
            {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
    
      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

myproject/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

myproject/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

myproject/templates/includes/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}  <!--Here is_bound means form has data and it returns True if form has data and false if form does not have-->
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

myproject/templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Django Boards? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

myproject/templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

myproject/templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myproject/templates/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}

    <div class="mb-4">
      <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Topic</th>
          <th>Starter</th>
          <th>Replies</th>
          <th>Views</th>
          <th>Last Update</th>
        </tr>
      </thead>
      <tbody>
         {% for topic in board.topics.all %}  <!--here board.topic_set.all work if we remove the related_name field from the models-->
          <tr>
            <td>{{topic.subject}}</td>
            <td>{{topic.starter.username}}</td>
            <td>0</td>
            <td>0</td>
            <td>{{topic.last_updated}}</td>
          </tr>
        {% endfor %}
      </tbody>

    </table>
{% endblock %}